
name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: cd docs/.vitepress/dist
      - name: Deploy # 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          repository-name: xugaoyang/vitepress-demo
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # 部署后提交到那个分支
          folder: docs/.vitepress/dist # 这里填打包好的目录名称